# Generated by Django 4.0.5 on 2022-06-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='modificação',
            new_name='modificado',
        ),
    ]
